import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center p-4 bg-blue-gray-600 text-white">
          <Link href="/">
            <h1 className="text-lg">Movie App</h1>
          </Link>
          <nav>
            <ul className="flex justify-between items-center">
              <li>
                <Link
                  href={"/add"}
                  className="bg-gray-500 p-2 shadow-lg rounded-lg"
                >
                  Add Movie
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
